In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.0.0'

In [3]:
#Constants

tensor = tf.constant([[23,4],[32,51]])

In [4]:
tensor

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [5]:
#Obtain the shape of tensor
tensor.shape

TensorShape([2, 2])

In [6]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy, sin necesidad de una session
numpy_tensor = np.array([[23,  4], [32, 51]])

In [7]:
# Podemos convertir un array de numpy a un tensor de TensorFlow directamente
tensor_from_numpy = tf.constant(numpy_tensor)

In [8]:
tensor_from_numpy

<tf.Tensor: id=1, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [9]:
# Variables

In [10]:
#Define and Show
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [11]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [12]:
#change value of tensor variable
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [13]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [14]:
#Operations with tensors
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=23, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [15]:
tensor + 2

<tf.Tensor: id=25, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

In [16]:
tensor * 5

<tf.Tensor: id=27, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

In [17]:
# Obtener los cuadrados de todos los números de un tensor de TensorFlow
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [18]:
# Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [19]:
np.dot(tensor, tensor)

array([[ 7, 10],
       [15, 22]])

In [20]:
#Using strings on TF 2.0
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=28, shape=(), dtype=string, numpy=b'TensorFlow'>

In [21]:
tf.strings.length(tf_string)

<tf.Tensor: id=29, shape=(), dtype=int32, numpy=10>

In [22]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=33, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119])>

In [23]:
#Store tensorflow constants as array string
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [24]:
# Iterar sobre un array de strings en TF
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
